import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "./components/nav";
import { navLinks } from "./data/navlinks";
import Footer from "./components/footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "SAA Website",
  description: "Generated by create next app",
  icons:"/saa_logo_png"
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NavBar navLinks={navLinks} />
        {children}
        <Footer />
      </body>
    </html>
  );
}
